### ISSUE TITLE
convergence issue

### ISSUE THREAD

**Issue by Yefeng0920** [cran/zcurve#1]
Hey František,

I used `zcurve` function (default settings) for my data, and I got a warning message `Warning: Model did not converge`. Sorry, it is hard to provide a reproducible example. Do you have any solution? Might tune the fitting algorithm hyperparameters via `control` augment?

Best,
Yefeng

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Yefeng0920** [comment]
I resolved the issue of convergence by adjusting the EM specifications. @FBartos @gaborcsardi  I also would be grateful, if you would like to tell me how to fit a collection of z values without truncation at 1.96. I mean z-curve only uses the statistically significant z-values to fit the mixture model. But how to use all z values regardless of the statistical significance. The reason why I ask this is because I want to test if a dataset without publication bias (this can be guaranteed by Registered Reports), the EDR derived from a mixture model fitted with only statistically significant z-values should be similar to that fitted with all z-values regardless of the statistical significance.

Best,
Yefeng

**Comment by Yefeng0920** [comment]
> Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

Sorry for the inconvenience. Now I move to the BugReports.
